name: Playwright QA Automation

on:
  push:
    branches: [ main ]

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run Playwright Script 23f2001645@ds.study.iitm.ac.in
        run: node scripts/scrape.js
